server:
  port: 8001
spring:
  application:
    name: lgame-registry
eureka:
  instance:
    hostname: localhost
  client:
#\u6b64\u5ba2\u6237\u7aef\u662f\u5426\u83b7\u53d6eureka\u670d\u52a1\u5668\u6ce8\u518c\u8868\u4e0a\u7684\u6ce8\u518c\u4fe1\u606f\uff0c\u9ed8\u8ba4\u4e3atrue
    fetch-registry: false
#\u662f\u5426\u6ce8\u518c\u81ea\u5df1
    register-with-eureka: false
  server:
#\u662f\u5426\u5f00\u542f\u81ea\u6211\u4fdd\u62a4\u6a21\u5f0f
    enable-self-preservation: false
