server:
 port: 8083
 servlet:
  context-path: /lgame-sms
    
#服务访问context-path   
eureka:
  instance:
    metadata-map:
      management:
        context-path: /lgame-sms/actuator
    health-check-url: http://localhost:${server.port}/lgame-sms/actuator/health
    status-page-url: http://localhost:${server.port}/lgame-sms/actuator/info
    home-page-url: http://localhost:${server.port}/
       
#mybatis\u914d\u7f6e
mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml

smsParam:
#\u77ed\u4fe1\u53d1\u9001--\u6d4b\u8bd5IP
 smsUrl: http://192.168.101.64/api/p/sms/sms/batchSend
#\u77ed\u4fe1\u53d1\u9001--\u6d4b\u8bd5\u5408\u4f5c\u65b9ID 
 smsPartnerId: 2000035
#\u77ed\u4fe1\u53d1\u9001--\u6d4b\u8bd5\u5e94\u7528\u7f16\u53f7 
 smsAppId: 24346KAQYFS38UX1C
#\u77ed\u4fe1\u53d1\u9001--\u6d4b\u8bd5\u8fde\u63a5\u79d8\u94a5 
 smsAccesskeysecret: O0bbb3b6W87b80T8b4b6438V9b2Q[N9
#\u6d4b\u8bd5\u73af\u5883\u8df3\u8fc7\u77ed\u4fe1\u9a8c\u8bc1\u7801\u53d1\u9001
 smsAllowsendpm: true
 
feign:
 client:
   config:
     default:
       connectTimeout: 300000
       readTimeout: 300000
        