server:
  port: 8085
  servlet:
   context-path: /lgame-portal

#mybatis\u914d\u7f6e
mybatis:
  mapper-locations:
    - classpath:mybatis/*.xml
    - classpath:mybatis/mapper/*.xml

#\u5f00\u542fspringboot-admin\u76d1\u63a7     
management: 
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      
secure:
  ignored:
    urls: #\u5b89\u5168\u8def\u5f84\u767d\u540d\u5355
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /sso/**
      - /checkSms/**
      - /sms/**
      - /portalUpload/**
      - /userAuth/**
      - /bank/**
      
jwt:
  tokenHeader: Authorization #JWT\u5b58\u50a8\u7684\u8bf7\u6c42\u5934
  secret: mall-portal-secret #JWT\u52a0\u89e3\u5bc6\u4f7f\u7528\u7684\u5bc6\u94a5
  expiration: 604800 #JWT\u7684\u8d85\u671f\u9650\u65f6\u95f4(60*60*24)
  tokenHead: Bearer #JWT\u8d1f\u8f7d\u4e2d\u62ff\u5230\u5f00\u5934
  
#\u5e38\u91cf\u914d\u7f6e
constant:
 smUrl: http://127.0.0.1:8083/lgame-sms/sms/sendSms
 
feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000

#拦截器拦截路径
url:
 excludeUrl: 
     - /portalUpload/** 
 speUrl:
   - /sso/**
   - /sso/refreshToken   
#request参数用户对象
 requestUser: REQUEST_USER  



